// <auto-generated />
using KindleKeep.Api.Infrastructure.Data;
using KindleKeep.Api.Infrastructure.Data.CompiledModels;
using Microsoft.EntityFrameworkCore.Infrastructure;

#pragma warning disable 219, 612, 618
#nullable disable

[assembly: DbContextModel(typeof(KindleDbContext), typeof(KindleDbContextModel))]
