// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace KindleKeep.Api.Infrastructure.Data.CompiledModels
{
    public partial class KindleDbContextModel
    {
        private KindleDbContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("e8f72ff0-1d95-445c-8e82-96636ce51a6e"), entityTypeCount: 2)
        {
        }

        partial void Initialize()
        {
            var monitorTarget = MonitorTargetEntityType.Create(this);
            var user = UserEntityType.Create(this);

            MonitorTargetEntityType.CreateForeignKey1(monitorTarget, user);

            MonitorTargetEntityType.CreateAnnotations(monitorTarget);
            UserEntityType.CreateAnnotations(user);

            AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);
            AddAnnotation("ProductVersion", "10.0.7");
            AddAnnotation("Relational:MaxIdentifierLength", 63);
        }
    }
}
