// <auto-generated />
using System;
using KindleKeep.Api.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace kindlekeep_api.Infrastructure.Data.Migrations
{
    [DbContext(typeof(KindleDbContext))]
    [Migration("20260426141622_AddTelemetryTables")]
    partial class AddTelemetryTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KindleKeep.Api.Core.Entities.MonitorTarget", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<char>("CurrentSecurityGrade")
                        .HasColumnType("character(1)");

                    b.Property<int>("CurrentUptimeStatus")
                        .HasColumnType("integer");

                    b.Property<string>("FriendlyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IntervalMinutes")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastAuditHash")
                        .HasColumnType("text");

                    b.Property<string>("RequestHeaders")
                        .HasColumnType("jsonb");

                    b.Property<int>("RequestTimeout")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("MonitorTargets");
                });

            modelBuilder.Entity("KindleKeep.Api.Core.Entities.SecurityAudit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("HasCsp")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasHsts")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasNosniff")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasXfo")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MonitorId")
                        .HasColumnType("uuid");

                    b.Property<string>("RawHeaders")
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("SslExpiryAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SslIssuer")
                        .HasColumnType("text");

                    b.Property<string>("TlsVersion")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MonitorId");

                    b.ToTable("SecurityAudits");
                });

            modelBuilder.Entity("KindleKeep.Api.Core.Entities.UptimeLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<bool>("IsColdStart")
                        .HasColumnType("boolean");

                    b.Property<int>("LatencyMs")
                        .HasColumnType("integer");

                    b.Property<Guid>("MonitorId")
                        .HasColumnType("uuid");

                    b.Property<int?>("StatusCode")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MonitorId");

                    b.HasIndex("Timestamp");

                    b.ToTable("UptimeLogs");
                });

            modelBuilder.Entity("KindleKeep.Api.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AuthProvider")
                        .HasColumnType("integer");

                    b.Property<string>("AvatarUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MonitorLimit")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("KindleKeep.Api.Core.Entities.MonitorTarget", b =>
                {
                    b.HasOne("KindleKeep.Api.Core.Entities.User", "User")
                        .WithMany("Monitors")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("KindleKeep.Api.Core.Entities.SecurityAudit", b =>
                {
                    b.HasOne("KindleKeep.Api.Core.Entities.MonitorTarget", "Monitor")
                        .WithMany()
                        .HasForeignKey("MonitorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Monitor");
                });

            modelBuilder.Entity("KindleKeep.Api.Core.Entities.UptimeLog", b =>
                {
                    b.HasOne("KindleKeep.Api.Core.Entities.MonitorTarget", "Monitor")
                        .WithMany()
                        .HasForeignKey("MonitorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Monitor");
                });

            modelBuilder.Entity("KindleKeep.Api.Core.Entities.User", b =>
                {
                    b.Navigation("Monitors");
                });
#pragma warning restore 612, 618
        }
    }
}
